//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCM.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCCM.Web.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        public static string Accessibility {
            get {
                return ResourceManager.GetString("Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliates.
        /// </summary>
        public static string Affiliates {
            get {
                return ResourceManager.GetString("Affiliates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Report.
        /// </summary>
        public static string AnnualReport {
            get {
                return ResourceManager.GetString("AnnualReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Forms.
        /// </summary>
        public static string ApplicationForms {
            get {
                return ResourceManager.GetString("ApplicationForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Start-Up.
        /// </summary>
        public static string BusinessStartup {
            get {
                return ResourceManager.GetString("BusinessStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By-Laws.
        /// </summary>
        public static string ByLaws {
            get {
                return ResourceManager.GetString("ByLaws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian Work Experience.
        /// </summary>
        public static string CanadianWorkExperience {
            get {
                return ResourceManager.GetString("CanadianWorkExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Mindling Services.
        /// </summary>
        public static string ChildMindling {
            get {
                return ResourceManager.GetString("ChildMindling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict of Interest Agreement.
        /// </summary>
        public static string CoIA {
            get {
                return ResourceManager.GetString("CoIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidentiality.
        /// </summary>
        public static string Confidentiality {
            get {
                return ResourceManager.GetString("Confidentiality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        public static string Constitution {
            get {
                return ResourceManager.GetString("Constitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earl Lagaya.
        /// </summary>
        public static string DeveloperName1 {
            get {
                return ResourceManager.GetString("DeveloperName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosel John Candoy.
        /// </summary>
        public static string DeveloperName2 {
            get {
                return ResourceManager.GetString("DeveloperName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donors.
        /// </summary>
        public static string Donors {
            get {
                return ResourceManager.GetString("Donors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Support.
        /// </summary>
        public static string EmploymentSupport {
            get {
                return ResourceManager.GetString("EmploymentSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English for General Purposes.
        /// </summary>
        public static string EnglishForGeneral {
            get {
                return ResourceManager.GetString("EnglishForGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event&apos;s Reports.
        /// </summary>
        public static string EventsReports {
            get {
                return ResourceManager.GetString("EventsReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filipino Seniors Project.
        /// </summary>
        public static string FilipinoSeniorsProject {
            get {
                return ResourceManager.GetString("FilipinoSeniorsProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Statements.
        /// </summary>
        public static string FinancialStatements {
            get {
                return ResourceManager.GetString("FinancialStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founders.
        /// </summary>
        public static string Founders {
            get {
                return ResourceManager.GetString("Founders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of PCCM.
        /// </summary>
        public static string HistortyOfPCCM {
            get {
                return ResourceManager.GetString("HistortyOfPCCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing Information.
        /// </summary>
        public static string HousingInformation {
            get {
                return ResourceManager.GetString("HousingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string Individual {
            get {
                return ResourceManager.GetString("Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Search.
        /// </summary>
        public static string JobSearch {
            get {
                return ResourceManager.GetString("JobSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Search Workshops.
        /// </summary>
        public static string JobSearchWorkshops {
            get {
                return ResourceManager.GetString("JobSearchWorkshops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Training.
        /// </summary>
        public static string LanguageTraining {
            get {
                return ResourceManager.GetString("LanguageTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use &amp; Policies.
        /// </summary>
        public static string Legals {
            get {
                return ResourceManager.GetString("Legals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentorship.
        /// </summary>
        public static string Mentorship {
            get {
                return ResourceManager.GetString("Mentorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        public static string MissionAndValues {
            get {
                return ResourceManager.GetString("MissionAndValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomination for Board of Director.
        /// </summary>
        public static string NominationForBoardOfDirector {
            get {
                return ResourceManager.GetString("NominationForBoardOfDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officers.
        /// </summary>
        public static string Officers {
            get {
                return ResourceManager.GetString("Officers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practicum Opportunities.
        /// </summary>
        public static string PracticumOpportunities {
            get {
                return ResourceManager.GetString("PracticumOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professionals.
        /// </summary>
        public static string Professionals {
            get {
                return ResourceManager.GetString("Professionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string Programs {
            get {
                return ResourceManager.GetString("Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental of Facility.
        /// </summary>
        public static string RentalOfFacility {
            get {
                return ResourceManager.GetString("RentalOfFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement.
        /// </summary>
        public static string Settlement {
            get {
                return ResourceManager.GetString("Settlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCCM.
        /// </summary>
        public static string ShortWebTitle {
            get {
                return ResourceManager.GetString("ShortWebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skilled Worker.
        /// </summary>
        public static string SkilledWorker {
            get {
                return ResourceManager.GetString("SkilledWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoken Tagalog.
        /// </summary>
        public static string SpokenTagalog {
            get {
                return ResourceManager.GetString("SpokenTagalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsors.
        /// </summary>
        public static string Sponsors {
            get {
                return ResourceManager.GetString("Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffs.
        /// </summary>
        public static string Staffs {
            get {
                return ResourceManager.GetString("Staffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteering.
        /// </summary>
        public static string Volunteering {
            get {
                return ResourceManager.GetString("Volunteering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer Opportunities.
        /// </summary>
        public static string VolunteerOpportunities {
            get {
                return ResourceManager.GetString("VolunteerOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteers.
        /// </summary>
        public static string Volunteers {
            get {
                return ResourceManager.GetString("Volunteers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer Stories and Testimonies.
        /// </summary>
        public static string VolunteerStories {
            get {
                return ResourceManager.GetString("VolunteerStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk-In Counceling.
        /// </summary>
        public static string WalkInCounceling {
            get {
                return ResourceManager.GetString("WalkInCounceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippine Canadian Centre of Manitoba.
        /// </summary>
        public static string WebTitle {
            get {
                return ResourceManager.GetString("WebTitle", resourceCulture);
            }
        }
    }
}
